"""
PDF Credit Risk Report Generator

Generates comprehensive credit analysis reports for each business using ReportLab.
Includes sections for business profile, credit score, fraud risk, turnover estimation,
GST filing analysis, vendor-customer network, and key risk factors.
Embeds visualization charts generated by the visualizations module.
"""

import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image, PageBreak, HRFlowable,
)

from visualizations.turnover_chart import calculate_turnover_metrics
from credit_scoring.scorer import classify_risk_band


def _safe_text(text):
    """Sanitize text for ReportLab - replace problematic Unicode chars."""
    if not isinstance(text, str):
        text = str(text)
    replacements = {
        '\u20b9': 'Rs.',
        '\u26a0': '[!]',
        '\u2014': '-',
        '\u2013': '-',
        '\u2018': "'",
        '\u2019': "'",
        '\u201c': '"',
        '\u201d': '"',
        '\u2022': '*',
    }
    for char, repl in replacements.items():
        text = text.replace(char, repl)
    text = text.encode('latin-1', errors='replace').decode('latin-1')
    return text


def _get_styles():
    """Create custom report styles."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="ReportTitle",
        parent=styles["Title"],
        fontSize=22,
        textColor=colors.HexColor("#1a237e"),
        spaceAfter=6,
        alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        name="SectionHeader",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=colors.HexColor("#1565C0"),
        spaceBefore=16,
        spaceAfter=8,
        borderWidth=1,
        borderColor=colors.HexColor("#1565C0"),
        borderPadding=4,
    ))
    styles.add(ParagraphStyle(
        name="SubHeader",
        parent=styles["Heading3"],
        fontSize=11,
        textColor=colors.HexColor("#333333"),
        spaceBefore=8,
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name="BodyText2",
        parent=styles["BodyText"],
        fontSize=10,
        leading=14,
        alignment=TA_JUSTIFY,
    ))
    styles.add(ParagraphStyle(
        name="AlertRed",
        parent=styles["BodyText"],
        fontSize=10,
        textColor=colors.HexColor("#D32F2F"),
        fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        name="AlertGreen",
        parent=styles["BodyText"],
        fontSize=10,
        textColor=colors.HexColor("#388E3C"),
        fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        name="AlertOrange",
        parent=styles["BodyText"],
        fontSize=10,
        textColor=colors.HexColor("#F57F17"),
        fontName="Helvetica-Bold",
    ))

    return styles


def generate_pdf_report(business, charts_dir, output_dir):
    """
    Generate a full PDF credit risk report for a business.

    Args:
        business: Complete business dictionary with scores and explanations
        charts_dir: Directory containing pre-generated chart images
        output_dir: Directory to save the PDF report

    Returns:
        Path to the generated PDF file
    """
    os.makedirs(output_dir, exist_ok=True)

    gstin = business["business_identity"]["gstin"]
    filepath = os.path.join(output_dir, "report_" + gstin + ".pdf")

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
    )

    styles = _get_styles()
    elements = []

    # === TITLE PAGE ===
    elements.append(Spacer(1, 40))
    elements.append(Paragraph("MSME Credit Risk Report", styles["ReportTitle"]))
    elements.append(Spacer(1, 8))
    elements.append(HRFlowable(
        width="100%", thickness=2,
        color=colors.HexColor("#1565C0")
    ))
    elements.append(Spacer(1, 12))

    identity = business["business_identity"]
    title_data = [
        ["Business Name", _safe_text(identity["legal_name"])],
        ["Trade Name", _safe_text(identity["trade_name"])],
        ["GSTIN", identity["gstin"]],
        ["PAN", identity["pan"]],
        ["Report Date", datetime.now().strftime("%d %B %Y")],
    ]
    title_table = Table(title_data, colWidths=[140, 300])
    title_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#555555")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(title_table)
    elements.append(Spacer(1, 20))

    # === SECTION 1: BUSINESS PROFILE ===
    elements.append(Paragraph("1. Business Profile", styles["SectionHeader"]))

    profile_data = [
        ["Constitution", _safe_text(identity.get("business_constitution", "N/A"))],
        ["Sector", _safe_text(identity.get("sector", "N/A"))],
        ["Location", _safe_text(identity.get("business_location", "N/A"))],
        ["Registration Date", identity.get("registration_date", "N/A")],
        ["Business Age", str(identity.get("business_age", 0)) + " years"],
        ["Sector Risk Score", str(identity.get("risk_sector_score", 0)) + "/10"],
    ]
    profile_table = Table(profile_data, colWidths=[160, 300])
    profile_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F5F5F5")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#E0E0E0")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(profile_table)

    # === SECTION 2: CREDIT SCORE ===
    elements.append(Paragraph("2. Credit Score Analysis", styles["SectionHeader"]))

    score = business.get("credit_score", 0)
    risk_band = classify_risk_band(score)

    if score >= 700:
        score_style = styles["AlertGreen"]
    elif score >= 500:
        score_style = styles["AlertOrange"]
    else:
        score_style = styles["AlertRed"]

    elements.append(Paragraph("Credit Score: " + str(score) + " / 900", score_style))
    elements.append(Paragraph("Risk Band: " + risk_band, score_style))
    elements.append(Spacer(1, 8))

    gauge_path = os.path.join(charts_dir, "gauge_" + gstin + ".png")
    if os.path.exists(gauge_path):
        img = Image(gauge_path, width=350, height=175)
        img.hAlign = 'CENTER'
        elements.append(img)

    # === SECTION 3: FRAUD RISK ===
    elements.append(Paragraph("3. Fraud Risk Assessment", styles["SectionHeader"]))

    fraud_prob = business.get("fraud_probability", 0)

    if fraud_prob >= 0.5:
        fraud_style = styles["AlertRed"]
    elif fraud_prob >= 0.3:
        fraud_style = styles["AlertOrange"]
    else:
        fraud_style = styles["AlertGreen"]

    elements.append(Paragraph(
        "Fraud Probability: " + str(round(fraud_prob * 100)) + "%", fraud_style
    ))

    fraud_info = business.get("fraud_indicators", {})
    indicators = fraud_info.get("fraud_indicators", [])
    if indicators:
        elements.append(Paragraph("Detected Anomalies:", styles["SubHeader"]))
        for ind in indicators:
            severity_colors = {
                "critical": "#D32F2F",
                "high": "#E65100",
                "medium": "#F57F17",
                "low": "#2E7D32",
            }
            sc = severity_colors.get(ind["severity"], "#333333")
            sev_upper = ind["severity"].upper()
            desc = _safe_text(ind["description"])
            text = '<font color="' + sc + '">[!] [' + sev_upper + ']</font> ' + desc
            elements.append(Paragraph(text, styles["BodyText2"]))

    elements.append(PageBreak())

    # === SECTION 4: TURNOVER ESTIMATION ===
    elements.append(Paragraph("4. Turnover Estimation", styles["SectionHeader"]))

    metrics = calculate_turnover_metrics(business)
    turnover_data = [
        ["Metric", "Value"],
        ["Estimated Annual Turnover", "Rs." + format(int(metrics["estimated_annual_turnover"]), ",")],
        ["Monthly Average Revenue", "Rs." + format(int(metrics["monthly_average_revenue"]), ",")],
        ["Growth Rate (Annual)", str(round(metrics["growth_rate"] * 100, 1)) + "%"],
        ["Volatility Index", str(round(metrics["volatility_index"], 3))],
    ]
    turnover_table = Table(turnover_data, colWidths=[200, 250])
    turnover_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1565C0")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#F5F5F5")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#E0E0E0")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(turnover_table)
    elements.append(Spacer(1, 10))

    turnover_path = os.path.join(charts_dir, "turnover_" + gstin + ".png")
    if os.path.exists(turnover_path):
        img = Image(turnover_path, width=480, height=170)
        elements.append(img)

    # === SECTION 5: GST FILING ANALYSIS ===
    elements.append(Paragraph("5. GST Filing Analysis", styles["SectionHeader"]))

    gst = business.get("gst_behavior", {})
    raw_late = gst.get("late_filings_count", 0)
    raw_months = gst.get("months_not_filed", 0)

    # Check amnesty status
    try:
        from utils.amnesty_config import is_any_amnesty_active, get_active_amnesty_windows
        amnesty_active = is_any_amnesty_active()
        active_windows = get_active_amnesty_windows()
    except Exception:
        amnesty_active = False
        active_windows = []

    gst_data = [
        ["Filing Frequency", str(gst.get("gst_filing_frequency", "N/A"))],
        ["Late Filings", str(raw_late) + (" (amnesty: suppressed to 0)" if amnesty_active and raw_late > 0 else "")],
        ["Months Not Filed", str(raw_months) + (" (amnesty: suppressed to 0)" if amnesty_active and raw_months > 0 else "")],
        ["Cancellation History", "Yes" if gst.get("gst_cancellation_history") else "No"],
        ["Multiple Registrations", "Yes" if gst.get("multiple_gst_registrations") else "No"],
    ]
    gst_table = Table(gst_data, colWidths=[180, 280])
    gst_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F5F5F5")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#E0E0E0")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(gst_table)

    # ── GST Amnesty Adjustment Notice ──
    if amnesty_active:
        elements.append(Spacer(1, 8))
        amnesty_quarters = ", ".join(w.get("quarter", "N/A") for w in active_windows)
        amnesty_box_data = [
            ["GST AMNESTY SCHEME ACTIVE"],
            ["Quarter(s): " + amnesty_quarters],
        ]
        adj_rows = []
        if raw_late > 0:
            adj_rows.append("late_filings_count: " + str(raw_late) + " -> 0 (suppressed)")
        if raw_months > 0:
            adj_rows.append("months_not_filed: " + str(raw_months) + " -> 0 (suppressed)")
        if raw_late > 0 or raw_months > 0:
            adj_rows.append("gst_compliance_score: recalculated without late-filing penalties")
            adj_rows.append("filing_gap_score: reset to 0.0")
        if adj_rows:
            amnesty_box_data.append(["Feature Adjustments:"])
            for row in adj_rows:
                amnesty_box_data.append(["  " + row])
        amnesty_box_data.append(["Note: Model weights were NOT retrained. Adjustments applied at feature layer."])

        amnesty_table = Table(amnesty_box_data, colWidths=[460])
        amnesty_table.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (0, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (0, 0), 11),
            ("TEXTCOLOR", (0, 0), (0, 0), colors.HexColor("#1565C0")),
            ("FONTSIZE", (0, 1), (-1, -1), 9),
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#E3F2FD")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#1565C0")),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ]))
        elements.append(amnesty_table)
    else:
        if gst.get("late_filings_count", 0) >= 5:
            late_count = str(gst["late_filings_count"])
            elements.append(Paragraph(
                "[!] High late filings: " + late_count + " late filings detected",
                styles["AlertRed"]
            ))
    if gst.get("gst_cancellation_history"):
        elements.append(Paragraph(
            "[!] GST registration was cancelled - significant red flag",
            styles["AlertRed"]
        ))

    # === SECTION 6: VENDOR-CUSTOMER NETWORK ===
    elements.append(Paragraph("6. Vendor-Customer Network", styles["SectionHeader"]))

    network = business.get("network_data", {})
    dep_val = network.get("dependency_on_single_customer", 0)
    circular_trades = network.get("circular_trades", [])
    net_data = [
        ["Vendors", str(network.get("vendor_count", 0))],
        ["Customers", str(network.get("customer_count", 0))],
        ["Concentration Ratio (HHI)", str(round(network.get("customer_concentration_ratio", 0), 4))],
        ["Max Single Customer %", str(round(dep_val * 100)) + "%"],
        ["Circular Trades Detected", str(len(circular_trades))],
    ]
    net_table = Table(net_data, colWidths=[180, 280])
    net_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F5F5F5")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#E0E0E0")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(net_table)

    # ── Fraud Ring Detail ──
    if circular_trades:
        elements.append(Spacer(1, 10))
        elements.append(Paragraph("Circular Fund Rotation (Fraud Rings)", styles["SubHeader"]))
        elements.append(Paragraph(
            "The following closed-loop money rotation patterns were detected in the "
            "vendor-customer transaction graph. Each ring represents UPI funds being "
            "rotated among connected MSMEs to artificially inflate transaction velocity.",
            styles["BodyText2"]
        ))
        elements.append(Spacer(1, 6))

        ring_header = [["Ring #", "Entities in Loop", "Rotated Funds (Rs.)"]]
        ring_rows = []
        for idx, ct in enumerate(circular_trades, 1):
            path = ct.get("path", [])
            # Abbreviate long GSTINs for readability
            path_labels = []
            for node in path:
                if node == gstin:
                    path_labels.append("TARGET")
                elif len(node) > 10:
                    path_labels.append(node[:6] + "..")
                else:
                    path_labels.append(node)
            path_str = _safe_text(" -> ".join(path_labels))
            funds = ct.get("rotated_funds", 0)
            funds_str = "Rs." + format(int(funds), ",") if funds else "Unknown"
            ring_rows.append([str(idx), path_str, funds_str])

        ring_table = Table(ring_header + ring_rows, colWidths=[50, 300, 110])
        ring_table.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#D32F2F")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#FFEBEE")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#D32F2F")),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#FFCDD2")),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        elements.append(ring_table)

        elements.append(Spacer(1, 6))
        elements.append(Paragraph(
            "[!] ALERT: " + str(len(circular_trades)) + " closed-loop fund rotation pattern(s) detected. "
            "These entities may be artificially inflating transaction velocity scores.",
            styles["AlertRed"]
        ))
    else:
        elements.append(Spacer(1, 6))
        elements.append(Paragraph(
            "No circular fund rotation patterns detected in the transaction network.",
            styles["AlertGreen"]
        ))

    # ── Network Graph Image ──
    network_path = os.path.join(charts_dir, "network_" + gstin + ".png")
    if os.path.exists(network_path):
        elements.append(Spacer(1, 8))
        img = Image(network_path, width=400, height=330)
        elements.append(img)

    elements.append(PageBreak())

    # === SECTION 7: KEY RISK FACTORS ===
    elements.append(Paragraph("7. Key Risk Factors", styles["SectionHeader"]))

    explanations = business.get("explanations", [])
    if explanations:
        for exp in explanations:
            safe_exp = _safe_text(exp)
            stripped = safe_exp.strip()
            if stripped == "---":
                elements.append(HRFlowable(
                    width="80%", thickness=0.5,
                    color=colors.HexColor("#CCCCCC")
                ))
            elif stripped.startswith("[!]") or stripped.startswith("- "):
                elements.append(Paragraph(safe_exp, styles["AlertOrange"]))
            elif stripped.startswith("+ "):
                elements.append(Paragraph(safe_exp, styles["AlertGreen"]))
            else:
                elements.append(Paragraph(safe_exp, styles["BodyText2"]))
    else:
        elements.append(Paragraph("No specific risk factors identified.", styles["BodyText2"]))

    sales_path = os.path.join(charts_dir, "sales_" + gstin + ".png")
    if os.path.exists(sales_path):
        elements.append(Spacer(1, 12))
        elements.append(Paragraph("Monthly Sales Trend:", styles["SubHeader"]))
        img = Image(sales_path, width=480, height=200)
        elements.append(img)

    radar_path = os.path.join(charts_dir, "radar_" + gstin + ".png")
    if os.path.exists(radar_path):
        elements.append(Spacer(1, 12))
        elements.append(Paragraph("Risk Assessment Radar:", styles["SubHeader"]))
        img = Image(radar_path, width=350, height=350)
        elements.append(img)

    # === SECTION 8: LOAN DECISION ===
    elements.append(PageBreak())
    elements.append(Paragraph("8. Loan Recommendation", styles["SectionHeader"]))

    decision = business.get("loan_decision", {})
    if decision:
        dec = decision.get("decision", "N/A")
        dec_styles = {
            "APPROVE": styles["AlertGreen"],
            "REJECT": styles["AlertRed"],
            "REVIEW": styles["AlertOrange"],
        }
        dec_style = dec_styles.get(dec, styles["BodyText2"])

        elements.append(Paragraph("Decision: " + dec, dec_style))
        loan_amt = decision.get("recommended_loan_amount", 0)
        elements.append(Paragraph(
            "Recommended Loan: Rs." + format(loan_amt, ","),
            styles["BodyText2"]
        ))
        elements.append(Spacer(1, 8))

        reasons = decision.get("reasons", [])
        if reasons:
            elements.append(Paragraph("Reasoning:", styles["SubHeader"]))
            for r in reasons:
                elements.append(Paragraph("* " + _safe_text(r), styles["BodyText2"]))

    # Footer
    elements.append(Spacer(1, 30))
    elements.append(HRFlowable(
        width="100%", thickness=1,
        color=colors.HexColor("#CCCCCC")
    ))
    footer_style = ParagraphStyle(
        name="Footer", parent=getSampleStyleSheet()["Normal"],
        fontSize=8, textColor=colors.HexColor("#999999"),
        alignment=TA_CENTER,
    )
    footer_text = (
        "Report generated on " + datetime.now().strftime("%d %B %Y at %H:%M") +
        " | MSME Credit Risk Platform | Confidential"
    )
    elements.append(Paragraph(footer_text, footer_style))

    doc.build(elements)
    return filepath
